### ISSUE TITLE
Put "Show less common lifecycles" in the route

### ISSUE THREAD

**Issue by DannyDelott** [wojtekmaj/react-lifecycle-methods-diagram#1]
For the purposes of bookmarking, it would be really great if the option to "Show less common lifecycles" was in the route.

**Comment by wojtekmaj** [comment]
Hi Danny,
your setting should be saved once you toggle the checkbox, so when you enter the page again you will see the chart as you left it off - is that not enough?

**Comment by DannyDelott** [comment]
The current local storage solution works. I didn't realize it was doing that.

**Comment by DanZeuss** [comment]
There is a PR that usually "fixes" this issue.
