### ISSUE TITLE
When collapsed it should show “Commit phase” instead of “Pre-commit phase”

### ISSUE THREAD

**Issue by lrn2prgrm** [wojtekmaj/react-lifecycle-methods-diagram#13]
![image](https://user-images.githubusercontent.com/18663098/40029073-26a64d2e-57a8-11e8-8d98-d902d23f3257.png)
![image](https://user-images.githubusercontent.com/18663098/40029083-3352c282-57a8-11e8-814f-75270aa24c31.png)

**Comment by wojtekmaj** [comment]
Hi, thanks! This is now fixed. It was an issue with translation component :)
