### ISSUE TITLE
Suggest to add Vietnamese translation

### ISSUE THREAD

**Issue by ngohungphuc** [wojtekmaj/react-lifecycle-methods-diagram#20]
I would love to make a PR for Vietnamese translation since React community in Vietnam are quite big. 
Let me know what you think @wojtekmaj

**Comment by wojtekmaj** [comment]
Hey, sure thing, go ahead! The more, the better. Make sure you don't miss anything, pl-PL.json is the most up to date if you'd like to compare.

**Comment by ngohungphuc** [comment]
Hi @wojtekmaj please review this [PR](https://github.com/wojtekmaj/react-lifecycle-methods-diagram/pull/22)

Thank you
