### ISSUE TITLE
componentWillUnmount and refs to null?

### ISSUE THREAD

**Issue by Ciantic** [wojtekmaj/react-lifecycle-methods-diagram#24]
I started to wonder, does React set all the refs to null before it calls componentWillUnmount or after?

However the diagram does not tell? Which one is it?

![image](https://user-images.githubusercontent.com/64731/47428115-f7f89900-d79a-11e8-8575-159b63184199.png)

**Comment by wojtekmaj** [comment]
I believe that `componentWillUnmount` would happen before React updates DOM and refs. @gaearon am I right? Maybe we should move `componentWillUnmount` two rows up and extend "React updates DOM and refs"?

**Comment by Ciantic** [comment]
I think during unmount it updates the DOM after the componentWillUnmount. Because it's called "will". 

So maybe it needs a new block "React updates refs to null" before componentWillUnmount and another new block "React updates DOM" after componentWillUnmount
