### ISSUE TITLE
"Show less common lifecycles" shows more lifecycles - confusing wording

### ISSUE THREAD

**Issue by wojtekmaj** [wojtekmaj/react-lifecycle-methods-diagram#3]
As reported in #2, wording is confusing.

"Show less common lifecycles" means "Show me also those lifecycles which are less common" and NOT "Show me less lifecycles".

**Comment by TheNovel** [comment]
Hello!

I send pull request #4 to fixing this issue.

**Comment by klujanrosas** [comment]
Maybe `Show me the less common lifecycles" is a better choice for this? :thinking:

**Comment by wojtekmaj** [comment]
That would work too! @TheNovel suggested "Show me all lifecycles" and I came up with "Show also less common lifecycles" .

**Comment by samvk** [comment]
"Show less-common lifecycles"

**Comment by TheNovel** [comment]
Maybe close this issue? PR already sent.

**Comment by manuel-di-iorio** [comment]
"Show all lifecycles" is perfect.
