### ISSUE TITLE
Broken on Chrome

### ISSUE THREAD

**Issue by MichaelDimmitt** [wojtekmaj/react-lifecycle-methods-diagram#49]
specifically here:
http://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/

![Screen Shot 2019-07-29 at 5 33 37 PM](https://user-images.githubusercontent.com/11463275/62086853-b0bd9e00-b22d-11e9-8a34-990dec5e1314.png)

environment: macOS 10.14.5

**Comment by MichaelDimmitt** [comment]
Discovered while showing someone to the website via react docs: https://reactjs.org/docs/react-component.html

**Comment by MichaelDimmitt** [comment]
Here are the images found from a google search.
![image](https://user-images.githubusercontent.com/11463275/62086942-f67a6680-b22d-11e9-9ec3-efaf0ac098b0.png)

![image](https://user-images.githubusercontent.com/11463275/62087043-45c09700-b22e-11e9-8191-8d261f22d3a5.png)

**Comment by MichaelDimmitt** [comment]
@wojtekmaj

**Comment by wojtekmaj** [comment]
@MichaelDimmitt Thanks - should be working fine now.
