### ISSUE TITLE
Bug when displaying less common lifecycles

### ISSUE THREAD

**Issue by AndroidRio** [wojtekmaj/react-lifecycle-methods-diagram#5]
When checking the checkbox do display the less common lifecycles, a bug happens and changes the name of some of the states to `render`. You can see this in the print below

![image](https://user-images.githubusercontent.com/5436014/38618641-a7ce3cd8-3d70-11e8-8a59-dc3bda202f6d.png)

**Comment by samvk** [comment]
Also gets confused when loading the page with "Show less common lifecycles" already enabled and then toggling off.

![projects wojtekmaj pl_react-lifecycle-methods-diagram_](https://user-images.githubusercontent.com/12996081/38626509-c1aa6262-3d7a-11e8-99e3-cb255adc67b0.png)

**Comment by wojtekmaj** [comment]
Thanks for reporting! This should be now fixed.

**Comment by wojtekmaj** [comment]
BTW, that was related to recent introduction of i18n - if you want to contribute and help folks from your country to understand React - you now have a possibility! :)
