### ISSUE TITLE
useTranslation is being called way more than it should

### ISSUE THREAD

**Issue by ReactAcademyCa** [wojtekmaj/react-lifecycle-methods-diagram#55]
useTranslation() gets called way too much. Between 350 and 450 times per screen. (it depends on the screen).  Because it updates the state in a useEffect(), it gets re-rendered and called a few times. 

It should be called way less often (below 35 times per screen). 
You can easily see this by placing a **console.log()** in the main body of the **useTranslation()** function.

**Comment by wojtekmaj** [comment]
Reduced from 316 to 133 calls in default view via commits above. Most components are getting two updates: null (when language is not loaded yet) and with string (after language load). Other useTranslation calls are caused by other component updates.

**Comment by wojtekmaj** [comment]
Closing as useTranslation is now fine; we can work on reducing needless updates in some components requesting translations.

**Comment by ReactAcademyCa** [comment]
Thank you for the fix. This is a big improvement.
