### ISSUE TITLE
"Chinese(Taiwan)" is incorrect! ⚠️

### ISSUE THREAD

**Issue by iTonyYo** [wojtekmaj/react-lifecycle-methods-diagram#60]
![image](https://user-images.githubusercontent.com/5499703/83349661-3b4cbd80-a369-11ea-849f-ac567e638109.png)

"Chinese(Taiwan)" is is incorrect. "Chinese(Traditional)" is right! Chinese language, only the difference between simplified Chinese and traditional Chinese, there is no difference between regions.

You should avoid possible political problems.

@wojtekmaj

**Comment by wojtekmaj** [comment]
Chinese traditional is zh-hant, not zh-tw 🤔

**Comment by iTonyYo** [comment]
> Chinese traditional is zh-hant, not zh-tw 🤔

If for this reason, then you should include all of the following, Not just Taiwan in China.
- `zh-Hans`    简体中文(个人推荐)
- `zh-Hans-CN`    以简体中文书写的中国大陆用词
- `zh-Hans-HK`    以简体中文书写的香港地区用词
- `zh-Hant`    繁體中文
- `zh-Hant-HK`    以繁體中文書寫的香港地區用詞
- `zh-Hant-TW`    以繁體中文書寫的台灣地區用詞
- `yue`    粤语发音
- `cmn`    普通话或國語发音
- `yue-Hans`    以简体中文书写的粤语用词
- `zh-yue-Hans`    以简体中文书写的粤语用词(个人推荐)
- `yue-Hant`   以繁體中文書寫的粵語用詞
- `cmn-Hans`    以简体中文书写的普通话用词
- `zh-cmn-Hans`    以简体中文书写的普通话用词(个人推荐)
- `cmn-Hans-CN`    以简体中文书写的中国大陆普通话用词
- `cmn-Hant-HK`    以繁體中文書寫的香港地区普通話用詞
- `cmn-Hant-TW`    以繁體中文書寫的台湾地区國語用詞

**Comment by wojtekmaj** [comment]
Agreed - we gotta be consistent. I've decided to rename zh-CN to zh-Hans.

**Comment by wojtekmaj** [comment]
Fixed in 7dab3c4.
