### ISSUE TITLE
It would be great to have a title :)

### ISSUE THREAD

**Issue by milebza** [wojtekmaj/react-lifecycle-methods-diagram#9]
Something like 'React lifecycle methods'.

When sharing the online version with other people if I don't tell them beforehand what's the link about, it's not so easy to understand what's the diagram about at first glance.

**Comment by oerd** [comment]
This has been taken care of... there is a title and opengraph meta tags.
Unless you want to add meta tags for twitter, this looks safe to close.

```
<meta name="twitter:card" content=summary />
<meta name="twitter:creator" content=@wojtekmaj91 />
```

**Comment by milebza** [comment]
Looks great!
