### ISSUE TITLE
Add support for Urdu language

### ISSUE THREAD

**Issue by rabbanirizwan** [wojtekmaj/react-lifecycle-methods-diagram#97]
@wojtekmaj 
Urdu is currently missing from the available languages dropdown. I have added Urdu language support.

**Comment by rabbanirizwan** [comment]
@wojtekmaj  kindly give me access so I push my branch
<img width="1328" alt="Screenshot 2022-11-02 at 9 37 54 PM" src="https://user-images.githubusercontent.com/33807776/199548608-e0b48e90-c253-4ff7-a1b2-f33c91dc4ea6.png">

**Comment by wojtekmaj** [comment]
Please raise a PR.

**Comment by rabbanirizwan** [comment]
I do not have the right to push code

**Comment by rabbanirizwan** [comment]
#98 https://github.com/wojtekmaj/react-lifecycle-methods-diagram/pull/98
